<div>

    <form action="" method="POST">
    <?php foreach ($basketCards as $card): ?>
        <div class = 'container-fluid'>

        <table>
            <tr>
                <th><img src="<?= $card->getCard()->getImage(); ?>" alt=""></th>
                <th><?= $card->getCard()->getName(); ?></th>
                <td>$ <?= $card->getCard()->getPrice(); ?></td>
                <td>quantity: <?= $card->getQuantity() ; ?></td>
            </tr>
        </table>
        </div>

    <?php endforeach; ?>
    </form>
</div>
