<div class="row row-cols-1 row-cols-md-3 g-4">
    <?php

    foreach ($cards as $card){

            ?>
            <form action="/basket" method="post">
            <div class="col" style="margin-bottom: 30px">
                <div class="card h-100">
                    <img src="<?php echo $card->getImage(); ?>" class="card-img-top" alt="...">
                    <div class="card-body"><h5 class="card-title">
                            <?php
                            echo $card->getName();

                            ?>
                        </h5>
                        <p class="card-text">Это более длинная карта С вспомогательным текстом. Этот контент немного длиннее.</p>
                        <p class="card-text">
                            <?php
                            echo $card->getPrice()."$";

                            ?>
                        </p>
                    </div>
                </div>
                <button style="background-color: green;" class="btn product__btn" type="submit">Order</button>
            </div>
            </form>
        <?php } ?>

</div>