<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Bootstrap demo</title>
</head>
<body>
<div class="container-fluid">
    <h4>Registry</h4>
    <form method="POST">

        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email</label>
            <input name= "email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div>
            <?php
            if(array_key_exists('email', $errors)){
                echo "<font color = 'red'>{$errors['email']}</font>";
            }
            ?>
        </div>

        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input name= "pass" type="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div>
            <?php
            if(array_key_exists('password', $errors)){
                echo "<font color = 'red'>{$errors['password']}</font>";
            }
            ?>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
</body>
</html>