
<div class="container-fluid">
    <h4 align="center">Registry</h4>
    <form method="POST">

        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email</label>
            <input name= "email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div>
            <?php
            if(array_key_exists('email', $errors)){
                echo "<font color = 'red'>{$errors['email']}</font>";
            }
            ?>
        </div>

        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input name= "pass" type="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div>
            <?php
            if(array_key_exists('password', $errors)){
                echo "<font color = 'red'>{$errors['password']}</font>";
            }
            ?>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        <?php
        if (array_key_exists('log_error', $errors)){
            echo "<font color = 'red'>{$errors['log_error']}</font>";
        }

        ?>
    </form>
</div>
